name: M-E-T Connections
favicon: null
layout_spectrum: 0.36372
typography_spectrum: 0.60523
title: M-E-T Connections
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25bed5'
    - '#8b8a8f'
    - '#7e7d7f'
    - '#aaaaaa'
    - '#00ffff'
  brandStrength: 0.11029727454297245
  lightness: 0.5699676326476038
  saturation: 0.9381179141346365
  rhythmicContrast: 0.24937175936065614
purpose: []
